/**
 * Country-name ↔ ISO-3166 alpha-2 mapping.
 *
 * Azure Front Door access logs (`clientCountry_s`) and the KQL
 * `geo_info_from_ip_address()` function both report countries by **full name**
 * ("Israel", "Netherlands", "United States"), whereas FrontLens keys the
 * `country` filter — and `GeoRow.country` / the world map — on the **ISO-2
 * code** ("IL", "NL", "US"). The Log Analytics adapter uses this table to
 * translate between the two so live mode matches demo mode exactly.
 *
 * The base table is generated from the Unicode CLDR English region names; the
 * ALIASES layer adds the alternative spellings Azure's geo service is known to
 * emit (e.g. "Russian Federation" for RU) so lookups stay robust.
 */

/** Full English country name → ISO-3166 alpha-2. */
const NAME_TO_ISO2: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  "American Samoa": "AS",
  Andorra: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarctica: "AQ",
  "Antigua & Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bosnia & Herzegovina": "BA",
  Botswana: "BW",
  "Bouvet Island": "BV",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  "British Virgin Islands": "VG",
  Brunei: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Caribbean Netherlands": "BQ",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  "Christmas Island": "CX",
  "Cocos (Keeling) Islands": "CC",
  Colombia: "CO",
  Comoros: "KM",
  "Congo - Brazzaville": "CG",
  "Congo - Kinshasa": "CD",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  Croatia: "HR",
  Cuba: "CU",
  "Curaçao": "CW",
  Cyprus: "CY",
  Czechia: "CZ",
  "Côte d’Ivoire": "CI",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Eswatini: "SZ",
  Ethiopia: "ET",
  "Falkland Islands": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  "French Southern Territories": "TF",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Haiti: "HT",
  "Heard & McDonald Islands": "HM",
  Honduras: "HN",
  "Hong Kong SAR China": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  "Isle of Man": "IM",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  "Macao SAR China": "MO",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "MH",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  Micronesia: "FM",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  "Myanmar (Burma)": "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  "Norfolk Island": "NF",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Northern Mariana Islands": "MP",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  "Palestinian Territories": "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  "Pitcairn Islands": "PN",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "Réunion": "RE",
  Samoa: "WS",
  "San Marino": "SM",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  "Sint Maarten": "SX",
  Slovakia: "SK",
  Slovenia: "SI",
  "Solomon Islands": "SB",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Georgia & South Sandwich Islands": "GS",
  "South Korea": "KR",
  "South Sudan": "SS",
  Spain: "ES",
  "Sri Lanka": "LK",
  "St. Barthélemy": "BL",
  "St. Helena": "SH",
  "St. Kitts & Nevis": "KN",
  "St. Lucia": "LC",
  "St. Martin": "MF",
  "St. Pierre & Miquelon": "PM",
  "St. Vincent & Grenadines": "VC",
  Sudan: "SD",
  Suriname: "SR",
  "Svalbard & Jan Mayen": "SJ",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  "São Tomé & Príncipe": "ST",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  "Timor-Leste": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad & Tobago": "TT",
  Tunisia: "TN",
  Turkmenistan: "TM",
  "Turks & Caicos Islands": "TC",
  Tuvalu: "TV",
  "Türkiye": "TR",
  "U.S. Outlying Islands": "UM",
  "U.S. Virgin Islands": "VI",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  "Vatican City": "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  "Wallis & Futuna": "WF",
  "Western Sahara": "EH",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  "Åland Islands": "AX",
};

/**
 * Alternative spellings Azure's geo service / AFD `clientCountry_s` may emit
 * that differ from the CLDR names above. Keeps name→ISO2 resolution robust.
 */
const ALIASES: Record<string, string> = {
  "United States of America": "US",
  USA: "US",
  "Russian Federation": "RU",
  "Korea, Republic of": "KR",
  "Republic of Korea": "KR",
  "Korea (Republic of)": "KR",
  "Korea, Democratic People's Republic of": "KP",
  "Iran, Islamic Republic of": "IR",
  "Iran (Islamic Republic of)": "IR",
  "Syrian Arab Republic": "SY",
  "Viet Nam": "VN",
  "Lao People's Democratic Republic": "LA",
  "Taiwan, Province of China": "TW",
  Turkey: "TR",
  "Czech Republic": "CZ",
  "Macedonia, the former Yugoslav Republic of": "MK",
  Macedonia: "MK",
  Swaziland: "SZ",
  "Cote d'Ivoire": "CI",
  "Ivory Coast": "CI",
  "Cabo Verde": "CV",
  "Bolivia, Plurinational State of": "BO",
  "Venezuela, Bolivarian Republic of": "BO",
  "Tanzania, United Republic of": "TZ",
  "Moldova, Republic of": "MD",
  "Brunei Darussalam": "BN",
  "Hong Kong": "HK",
  Macao: "MO",
  Macau: "MO",
  "Palestine, State of": "PS",
  Palestine: "PS",
  "Congo, The Democratic Republic of the": "CD",
  "Congo (Kinshasa)": "CD",
  "Congo (Brazzaville)": "CG",
  "Holy See (Vatican City State)": "VA",
  "Vatican City State": "VA",
  Myanmar: "MM",
  Burma: "MM",
  "Republic of the Congo": "CG",
};

/** Reverse table: ISO-2 → canonical display name. */
const ISO2_TO_NAME: Record<string, string> = Object.fromEntries(
  Object.entries(NAME_TO_ISO2).map(([name, iso]) => [iso, name]),
);

/**
 * Resolve a full country name (as reported by Azure/AFD) to its ISO-2 code.
 * Returns the input unchanged if it already looks like an ISO-2 code, or `""`
 * for an empty/unknown value (so callers can group unknowns together).
 */
export function countryNameToIso2(name: string | null | undefined): string {
  if (!name) return "";
  const trimmed = name.trim();
  if (trimmed === "") return "";
  // Already an ISO-2 code (AFD occasionally emits codes for some edges).
  if (/^[A-Za-z]{2}$/.test(trimmed)) return trimmed.toUpperCase();
  return NAME_TO_ISO2[trimmed] ?? ALIASES[trimmed] ?? trimmed;
}

/** Resolve an ISO-2 code to a display name (falls back to the code itself). */
export function iso2ToCountryName(iso2: string | null | undefined): string {
  if (!iso2) return "";
  return ISO2_TO_NAME[iso2.toUpperCase()] ?? iso2;
}

/**
 * Given a set of ISO-2 codes (the `country` filter), return the full names to
 * match against AFD's `clientCountry_s`. Includes both the canonical name and
 * any aliases that map to the same code, so the KQL `in (...)` predicate
 * catches every spelling Azure might use.
 */
export function iso2ToCountryNames(iso2: string): string[] {
  const code = iso2.toUpperCase();
  const names = new Set<string>();
  const canonical = ISO2_TO_NAME[code];
  if (canonical) names.add(canonical);
  for (const [name, c] of Object.entries(ALIASES)) {
    if (c === code) names.add(name);
  }
  // If we don't recognise the code, fall back to matching the code literally.
  if (names.size === 0) names.add(iso2);
  return [...names];
}
